name: Validate renovate config

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/renovate.yml"
      - "renovate.json"

jobs:
  validate-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e # tag=v2

      - name: Validate renovate config
        run: npx -y --package renovate -- renovate-config-validator
